module XlsxTemplater
  # Some xlsx, such as generated by non-microsoft word, sometime make invalid xlsx. Its input stream returns Zip::NullInputStream. When it detected, this error is raised.
  InvalidInputError = Class.new(StandardError)

  module_function

  def log(str)
    puts str if ENV['DEBUG']
  end
end

require 'xlsx_templater/template_processor'
require 'xlsx_templater/xlsx_creator'
